<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="CustomerOrderList.aspx.cs" Inherits="Exam_Test.CustomerOrderList" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <asp:Button runat="server" ID="btnaddnew" OnClick="btnaddnew_Click" Text="Add New" />
        <asp:GridView ID="GridView1" runat="server" DataKeyNames="ID" OnRowDeleting="OnRowDeleting" EmptyDataText="No records has been added." AutoGenerateDeleteButton="true">
            <Columns>

                <asp:HyperLinkField DataNavigateUrlFields="ID" DataNavigateUrlFormatString="CustomerOrder.aspx?ID={0}" Text="UPDATE" />

               <%-- <asp:TemplateField HeaderText="Id" ItemStyle-Width="30">
                    <ItemTemplate>
                        <asp:HyperLink runat="server" NavigateUrl='<%# Eval("ID", "CustomerOrder.aspx?ID={0}") %>'
                            Text='<%# Eval("ID") %>' />
                    </ItemTemplate>
                </asp:TemplateField>--%>

            </Columns>
        </asp:GridView>
    </form>
</body>
</html>
